app/models.py
#from .. import db, login
from app import db, login
from datetime import datetime
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import UserMixin
from hashlib import md5
from datetime import datetime


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    about_me = db.Column(db.String(140))

    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User {self.username}>'

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return f'https://www.gravatar.com/avatar/{digest}?d=identicon&s={size}'


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'<Post {self.body}>'


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length
from flask_wtf import FlaskForm


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[
                             DataRequired(), Length(min=0, max=140)])
    submit = SubmitField('Submit')

app/__init__.py
from config import Config
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    #app.jinja_env.trim_blocks = True
    #app.jinja_env.lstrip_blocks = True

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')
    return app


#from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, request
from flask_login import current_user, login_required
from app.models import User
from datetime import datetime
from app.models import db
from app.main import bp
from app.main.forms import EditProfileForm


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/edit_profile')
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        return render_template(url_for('edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html', title='Edit Profile', form=form)


@bp.route('/', methods=('GET',))
@bp.route('/index', methods=('GET',))
@login_required
def index():
    posts = {}
    return render_template('main/index.html', title='Welcome to Quiz Hound!', posts=posts)


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = [
        {'author': user, 'body': 'Testing 1'},
        {'author': user, 'body': 'Testing 2'},
    ]
    return render_template('main/user.html', title='Profile', user=user, posts=posts)

app/templates/base.html
{% import 'macros/_macros.html' as macros %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='style.css') }}">
    <title>{{ macros.set_title(title, fallback='No title set!') }}</title>
</head>

<body>
    <nav>
        <ul class="nav navbar-nav">
            {{ macros.set_navlink('Home', 'main.index') }}
            {% if current_user.is_anonymous %}
            {{ macros.set_navlink('Login', 'auth.login') }}
            {% else %}
            {{ macros.set_navlink('Profile', 'main.user', username=current_user.username) }}
            {{ macros.set_navlink('Logout', 'auth.logout') }}
            {% endif %}
        </ul>
    </nav>
    <hr>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <main>{% block main %}{% endblock %}</main>
    <script src="{{ url_for('static', filename='jquery-3.3.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>

</html>

app/templates/macros/_macros.html
{% macro set_title(title, fallback) %}
{% if title %}
{{ title }}
{% else %}
{{ fallback }}
{% endif %}
{% endmacro %}

{% macro set_navlink(name, endpoint) %}
{% if request.endpoint.endswith(endpoint) %}
<li class="active">
    <a href="{{ url_for(endpoint, **kwargs) }}"> {{ name }} </a>
</li>
{% else %}
<li>
    <a href="{{ url_for(endpoint, **kwargs) }}"> {{ name }} </a>
</li>
{% endif %}
{% endmacro %}

{% macro render_field(field) %}
<dt>{{ field.label }}</dt>
<dd>
    {{ field(**kwargs)|safe }}
    {% if field.errors %}
    <ul class="errors">
        {% for error in field.errors %}
        <li style="color: red;">[{{ error }}]</li>
        {% endfor %}
    </ul>
    {% endif %}
</dd>
{% endmacro %}

app/templates/main/_post.html
<table>
    <tr valign="top">
        <td><img src="{{ post.author.avatar(48) }}"></td>
        <td>{{ post.author.username }} says:<br>{{ post.body }}</td>
    </tr>
</table>

app/templates/main/edit_profile.html
{% extends 'base.html' %}
{% import 'macros/_macros.html' as macros %}

{% block main %}
<h1>{{ title }}</h1>
<form action="post">
    <dl>
        {{ macros.render_field(form.username) }}
        {{ macros.render_field(form.about_me) }}
    </dl>
    {{ macros.render_field(form.submit) }}
</form>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}

{% block header %}
{% block title %}
{% endblock %}
{% endblock %}

{% block main -%}
<h1>Hi, {{ current_user.username }}!</h1>
{% for post in posts %}
<div>
    <p>{{ post.author.username }} says: <b>{{ post.body }}</b></p>
</div>
{% endfor %}
{%- endblock %}

app/templates/main/user.html
{% extends 'base.html' %}

{% block main %}
<table>
    <tr valign="top">
        <td><img src="{{ user.avatar(128) }}"></td>
        <td>
            <h1>User: {{ user.username }}</h1>
            {% if user.about_me %}<p>{{ user.about_me|safe }}</p>{% endif %}
            {% if user.last_seen %}<p>Last seen on: {{ user.last_seen }}</p>{% endif %}
        </td>
    </tr>
</table>
    {% if user == current_user %}
    <p>
        <a href="{{ url_for('main.edit_profile') }}">Edit your profile</a>
    </p>
    {% endif %}
<hr>
{% for post in posts %}
{% include 'main/_post.html' %}
{% endfor %}
{% endblock %}